### ISSUE TITLE
Lava/Bio Generators Do Not Recognize Advanced Machine Cores (Tier 2+)

### ISSUE THREAD

**Issue by 8cher** [Rearth/Oritech#498]
### Issue description

After updating to FTB Skies 2 v1.5.2, Oritech’s Lava Generator and Bio Generator fail to recognize advanced Machine Cores (Tier 2 or higher). 
Despite using higher-tier cores, the GUI displays Machine Quality: 1 and behaves as a Tier 1 machine.

### Steps to reproduce

1. Build a Lava Generator or Bio Generator using Tier 2+ machine core.
2. Open the generator’s GUI → Observe Machine Quality: 1 (incorrect tier).
3. Attach extender and behaves as a Tier 1 machine.

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.194

### Oritech version

0.17.3

**Comment by rhullah** [comment]
This is also happening with the Fuel Generator.  No matter what machine core is used, the machine only get a Machine Quality of 1. Was this intentional?

**Comment by Rearth** [comment]
This is a bug. The quality is still set on the server, but isn't synced to the client, so the UI doesnt work. Attaching extenders should still work though, you just dont see them as connected in the UI. It'll be fixed in the next update.

**Comment by Rearth** [comment]
Fixed with b82b2d8307cf0a62b17cc4a17c471c1a1e6d5bac

**Comment by rhullah** [comment]
I finally got around to testing this and while the distance of the add-ons does now match the machine core quality, it still seems to be different than what it was before.

Before when using max machine core (for an add-on distance of 7) I could go out from any plug port on the machine 7 add-ons in all (5) directions forming a pyramid. It seems now that you can only go out in one direction instead of the five. If you then add more in another direction it takes away from the first 7 you placed. 

Is this intended? Should only one length of 7 be the max you can use?

**Comment by rhullah** [comment]
Nevermind, as I thought the pack I was playing had the latest version of Oritech but it didn't. I'll test it again once it's in the latest version.

**Comment by rhullah** [comment]
Huh, I thought this fix was in the v0.18.2 release, but I'm looking at it again and it's now saying it's in the v0.19.0 release which was just 6 hours ago.  Was this missed in previous release?

Because I did just check this in 0.18.2, and the limited behavior was still happening.

**Comment by Rearth** [comment]
I'm not sure I understand your issue. The addon behaviour was changed a few versions ago. If you want the old "layered extends" variant, there's a config option for it.

**Comment by rhullah** [comment]
I just didn't know if this new style of limiting the add-ons was intentional or not. But it sounds from your comment that it is intentional and if you have a machine core of 7 you can only go out 7 "once" not multiple times/directions. Sorry for my confusion, I missed that update.
